WEBHOOK_PASSPHRASE = None

LEVERAGE_TESTING = None
RISK_TESTING = None
API_KEY_TESTING = None
API_SECRET_TESTING = None

LEVERAGE_STRATEGY_TWO = None
RISK_STRATEGY_TWO = None
API_KEY_STRATEGY_TWO = None
API_SECRET_STRATEGY_TWO = None
