WEBHOOK_PASSPHRASE = 'WEBHOOK_PASSPHRASE'

LEVERAGE_TESTING = 5.0
RISK_TESTING = 1.0
API_KEY_TESTING = 'API_KEY_TESTING'
API_SECRET_TESTING = 'API_SECRET_TESTING'

LEVERAGE_STRATEGY_TWO = 5.0
RISK_STRATEGY_TWO = 1.0
API_KEY_STRATEGY_TWO = 'API_KEY_STRATEGY_TWO'
API_SECRET_STRATEGY_TWO = 'API_SECRET_STRATEGY_TWO'
