apiVersion: v1 
kind: PersistentVolumeClaim 
metadata:
  name: trading-bot-config
  namespace: trading
spec:
  storageClassName: hostpath-config
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
